const DATASET_URL='https://scoringapi.h2ohackathon.org/Challenge/json';
const fallback=[{name:'Tracy, CA',lat:37.7397,lng:-121.4252,snowpack:65,rainfall:105,reservoir:72,temp:89},{name:'Sacramento, CA',lat:38.58,lng:-121.49,snowpack:78,rainfall:96,reservoir:76,temp:84},{name:'Fresno, CA',lat:36.73,lng:-119.78,snowpack:62,rainfall:88,reservoir:69,temp:95}];
let selected=null,data=[]; const w={snowpack:.3,rainfall:.3,reservoir:.4};
let map=null, layer=null;
function initMap(){
  if(map) return;
  map=L.map('map').setView([37.25,-120.4],6);
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
  layer=L.layerGroup().addTo(map);
}
const pct=v=>v>1?v:v*100,norm=v=>Math.max(0,Math.min(1,pct(v)/100)); const wai=d=>Math.round((norm(d.snowpack)*w.snowpack+norm(d.rainfall)*w.rainfall+norm(d.reservoir)*w.reservoir)*100); const pred=x=>Math.max(0,x-(x<45?13:x<70?9:4)); const cls=x=>x>=70?'wai-safe':x>=40?'wai-warning':'wai-critical'; const status=x=>x>=70?'Safe':x>=40?'Warning':'Critical';
function adapt(r,i){const lat=Number(r.lat??r.latitude??r.y),lng=Number(r.lng??r.lon??r.longitude??r.x); if(!isFinite(lat)||!isFinite(lng)) return null; return {name:r.name??r.location??`Location ${i+1}`,lat,lng,snowpack:Number(r.snowpack??65),rainfall:Number(r.rainfall??100),reservoir:Number(r.reservoir??70),temp:Number(r.temp??88)};}
async function load(){try{const r=await fetch(DATASET_URL); if(!r.ok) throw new Error(`HTTP ${r.status}`); const p=await r.json(); const arr=(Array.isArray(p)?p:p.data)||[]; const n=arr.map(adapt).filter(Boolean); if(!n.length) throw new Error('No rows'); return n;}catch(e){bot(`Live dataset unavailable (${e.message}). Using fallback.`); return fallback;}}
function markers(rows){ if(!map) initMap(); layer.clearLayers(); rows.forEach(loc=>{const score=wai(loc),c=score>=70?'#31d96d':score>=40?'#f7d74b':'#ef5f5f'; const m=L.circleMarker([loc.lat,loc.lng],{radius:10,color:c,fillColor:c,fillOpacity:.92}).addTo(layer); m.bindTooltip(`${loc.name} • WAI ${score}`); m.on('click',()=>{selected={...loc,wai:score,prediction:pred(score)}; renderLocation(); setPage('overview'); bot(`${loc.name} selected.`);});}); tables();}
function renderLocation(){if(!selected)return; document.getElementById('locationCard').innerHTML=`<h3>${selected.name}</h3><p><b>WAI:</b> <span class='${cls(selected.wai)}'>${selected.wai} (${status(selected.wai)})</span></p><p><b>Snowpack:</b> ${pct(selected.snowpack).toFixed(0)}% of April 1 avg</p><p><b>Precip:</b> ${pct(selected.rainfall).toFixed(0)}% of avg</p><p><b>Reservoir:</b> ${pct(selected.reservoir).toFixed(0)}% capacity</p><p><b>Forecast:</b> ${selected.prediction} in 30 days</p>`;}
function tables(){const past=document.getElementById('pastTable'),present=document.getElementById('presentTable'),future=document.getElementById('futureTable'); past.innerHTML=present.innerHTML=future.innerHTML=''; data.forEach(d=>{const s=wai(d),f=pred(s); past.innerHTML+=`<tr><td>${d.name}</td><td class='${cls(s)}'>${Math.max(0,s-6)}</td><td>${pct(d.snowpack)-8}%</td><td>${pct(d.rainfall)-4}%</td><td>${pct(d.reservoir)-5}%</td></tr>`; present.innerHTML+=`<tr><td>${d.name}</td><td class='${cls(s)}'>${s}</td><td>${status(s)}</td><td>${s<40&&d.temp>90?'High dehydration risk':'Moderate'}</td></tr>`; future.innerHTML+=`<tr><td>${d.name}</td><td>${s}</td><td class='${cls(f)}'>${f}</td><td>${status(s)} → ${status(f)}</td></tr>`; });
 document.getElementById('pastSummary').innerHTML='<p>Past tab estimates previous seasonal context from current indicators.</p>'; document.getElementById('presentSummary').innerHTML='<p>Present tab shows current score, status, and health signal.</p>'; document.getElementById('futureSummary').innerHTML='<p>Future tab provides 30-day projection and risk shift.</p>';}
function add(role,t){const box=document.getElementById('locationCard');}
function bot(t){const log=document.getElementById('helpBtn');}
function answer(q){if(!selected) return 'Select a location first.'; q=q.toLowerCase(); if(q.includes('past'))return `Past estimate for ${selected.name}: WAI ${Math.max(0,selected.wai-6)}.`; if(q.includes('present'))return `Current WAI is ${selected.wai}.`; if(q.includes('future')||q.includes('forecast'))return `30-day WAI is ${selected.prediction}.`; if(q.includes('help'))return 'Use Past/Present/Future tabs plus map to make better water decisions.'; return `Status: ${status(selected.wai)}. Try asking past, present, or future.`;}
function setPage(n){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active')); document.getElementById(`page-${n}`).classList.add('active'); document.querySelectorAll('.tab-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===n));}
document.querySelectorAll('.tab-btn').forEach(b=>b.addEventListener('click',()=>setPage(b.dataset.page)));
document.getElementById('helpBtn').addEventListener('click',()=>setPage('help'));
document.getElementById('openMapBtn').addEventListener('click',()=>{ if(!map) initMap(); document.getElementById('mapModal').classList.add('active'); setTimeout(()=>map.invalidateSize(),50);});
document.getElementById('closeMapBtn').addEventListener('click',()=>document.getElementById('mapModal').classList.remove('active'));
document.getElementById('refreshDataBtn').addEventListener('click',async()=>{data=await load(); markers(data);});
document.getElementById('loginForm').addEventListener('submit',async(e)=>{e.preventDefault(); document.getElementById('loginScreen').classList.remove('active'); document.getElementById('appShell').classList.remove('hidden'); initMap(); data=await load(); markers(data);});
